#ifndef OS_PROXY_CONFIGURE_H
#define OS_PROXY_CONFIGURE_H

#define N_QUEUE_LISTEN_SOCKET 5

#define WORKER_BUFFER_SIZE 4096

#define HTTP_HEADER_PARSER_BUFFER_SIZE 128

#endif /* OS_PROXY_CONFIGURE_H */